trigger:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
  paths:
    include:
      - Activities/Cryptography/*
      - Activities/Activities.Cryptography.sln
variables:
  majorVersion: '1'
  minorVersion: '2'
  patchVersion: '0'
  revision: $[counter(variables['patchVersion'], 1)] #this will get reset when minor gets bumped.
  versionSuffix: ''
  versionNumber: '$(majorVersion).$(minorVersion).$(patchVersion)'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
   versionSuffix: 'alpha.$(revision)'
  ${{ if contains(variables['Build.SourceBranchName'], 'release') }}:
   versionSuffix: 'beta.$(revision)'

pr:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
      - feature/*
  paths:
    include:
      - Activities/Cryptography/*
      - Activities/Activities.Cryptography.sln

jobs:
  - template: "../.pipelines/jobs/ci.yml"
    parameters:
      BuildProject: "../Activities.Cryptography.sln"
      BuildConfiguration: "Release"
      BuildPlatform: "AnyCPU"
      rootPath: $(Build.SourcesDirectory)\Activities\Cryptography\
      packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
      restoreDependencies: 
        - "UiPath.Cryptography/UiPath.Cryptography.csproj"
        - "UiPath.Cryptography.Activities/UiPath.Cryptography.Activities.csproj"
      testList: 
        - "UiPath.Cryptography.Activities.Tests/UiPath.Cryptography.Activities.Tests.csproj"        
      versionReference: "CryptographyAssemblyInfo.cs"
      versionNumber: ${{ variables.packageVersion }}
