trigger:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
  paths:
    include:
      - Activities/Twilio/*
      - Activities/Activities.Twilio.sln

variables:
  majorVersion: '1'
  minorVersion: '1'
  patchVersion: '0'
  revision: $[counter(variables['patchVersion'], 1)] #this will get reset when minor gets bumped.
  versionSuffix: ''
  versionNumber: '$(majorVersion).$(minorVersion).$(patchVersion)'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
   versionSuffix: 'alpha.$(revision)'
  ${{ if contains(variables['Build.SourceBranchName'], 'release') }}:
   versionSuffix: 'beta.$(revision)'

pr:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
      - feature/*
  paths:
    include:
      - Activities/Twilio/*
      - Activities/Activities.Twilio.sln
      
jobs:
  - template: "../.pipelines/jobs/ci.yml"
    parameters:
      BuildProject: "../Activities.Twilio.sln"
      BuildConfiguration: "Release"
      BuildPlatform: "AnyCPU"
      rootPath: $(Build.SourcesDirectory)\Activities\Twilio\
      packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
      versionReference: "UiPath.Twilio.Activitie/Properties/AssemblyInfo.cs"
      versionNumber: ${{ variables.versionNumber }}
      versionSuffix: ${{ variables.versionSuffix }}