trigger:
  branches:
    include:
      - masters/Database/*
      - develop
      - release/Database/*
      - support/Database/*
  paths:
    include:
      - Activities/Database/*
      - Activities/Activities.Database.sln

variables:
  majorVersion: '1'
  minorVersion: '4'
  patchVersion: '0'
  revision: $[counter(variables['patchVersion'], 1)] #this will get reset when minor gets bumped.
  versionNumber: '$(majorVersion).$(minorVersion).$(patchVersion)'
  -template: "../.pipelines/variables/vars.yml"

pr:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
      - feature/*
  paths:
    include:
      - Activities/Database/*
      - Activities/Activities.Database.sln

jobs:
  - template: "../.pipelines/jobs/ci.yml"
    parameters:
      BuildProject: "../Activities.Database.sln"
      BuildConfiguration: "Release"
      BuildPlatform: "AnyCPU"
      rootPath: $(Build.SourcesDirectory)\Activities\Database\
      packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
      restoreDependencies: 
        - "UiPath.Database/UiPath.Database.csproj"
        - "UiPath.Database.Activities/UiPath.Database.Activities.csproj"
      testList: 
        - "UiPath.Database.Tests/UiPath.Database.Tests.csproj"
      versionReference: "DatabaseAssemblyVersion.cs"
      versionNumber: ${{ variables.versionNumber }}
      versionSuffix: ${{ variables.versionSuffix }}
